#if !defined(GENERATED_ASSET_ID_H) && defined(SNAIL_JUMPY_USE_PROCESSED_ASSETS)
#define GENERATED_ASSET_ID_H
enum {
SoundEffectID_sound_perform_ritual = 0,
SoundEffectID_sound_menu_move = 1,
SoundEffectID_sound_item_bought = 2,
SoundEffectID_sound_bell_tower_play = 3,
SoundEffectID_sound_item_dropped = 4,
SoundEffectID_sound_bellows_repaired = 5,
SoundEffectID_sound_test_music = 6,
SoundEffectID_sound_item_eaten = 7,
SoundEffectID_sound_move = 8,
SoundEffectID_sound_pipes_repaired = 9,
SoundEffectID_sound_open_door = 10,
SoundEffectID_sound_item_fed = 11,
SoundEffectID_sound_read = 12,
SoundEffectID_sound_open_map = 13,
SoundEffectID_sound_organ_play_broken = 14,
SoundEffectID_sound_setup_candles = 15,
SoundEffectID_sound_close_map = 16,
SoundEffectID_sound_organ_play_repaired = 17,
SoundEffectID_sound_pray = 18,
SoundEffectID_sound_item_taken = 19,
SoundEffectID_TOTAL = 20,

FontID_font_fancy = 0,
FontID_font_basic = 1,
FontID_font_basic_bold = 2,
FontID_font_basic2 = 3,
FontID_font_basic_lowercase = 4,
FontID_TOTAL = 5,

VariableID_goto_specific = 0,
VariableID_examine_invalid = 1,
VariableID_locked = 2,
VariableID_repair_cant = 3,
VariableID_auto_unlock = 4,
VariableID_setup_candles_carillon_pages = 5,
VariableID_repair_not_broken = 6,
VariableID_carillon_pages_bench_ghost_following = 7,
VariableID_move_invalid_room = 8,
VariableID_use_dont_know = 9,
VariableID_move_invalid_all = 10,
VariableID_setup_candles_cant = 11,
VariableID_use_dont_have = 12,
VariableID_carillon_pages_cathedral_singing = 13,
VariableID_exit_where = 14,
VariableID_perform_ritual_carillon_pages_inactive = 15,
VariableID_undo_message = 16,
VariableID_enter_where = 17,
VariableID_redo_message = 18,
VariableID_buy_callback_prompt = 19,
VariableID_event_carillon_pages = 20,
VariableID_ghost_enter = 21,
VariableID_perform_ritual_carillon_pages_wrong_room = 22,
VariableID_buy_callback_no = 23,
VariableID_ghost_leave = 24,
VariableID_theme = 25,
VariableID_event_ghost_playing_organ = 26,
VariableID_take_buy = 27,
VariableID_feed_no_eater = 28,
VariableID_take_buy_prompt = 29,
VariableID_feed_no_food = 30,
VariableID_perform_ritual_carillon_pages_no_book = 31,
VariableID_buy_static = 32,
VariableID_pray_response = 33,
VariableID_start_room = 34,
VariableID_buy_free = 35,
VariableID_pray_carillon_pages_bench = 36,
VariableID_buy_prompt = 37,
VariableID_buy_too_poor = 38,
VariableID_perform_ritual_carillon_pages_no_candles = 39,
VariableID_invalid_command = 40,
VariableID_pray_carillon_pages_cathedral = 41,
VariableID_eat_cant = 42,
VariableID_ambiguous_items = 43,
VariableID_eat_invalid = 44,
VariableID_room_too_small = 45,
VariableID_examine_none = 46,
VariableID_feed_carillon_pages_bench_ghost_pie = 47,
VariableID_perform_ritual_carillon_pages_successful = 48,
VariableID_TOTAL = 49,

ThemeID_theme_default = 0,
ThemeID_theme_planty = 1,
ThemeID_TOTAL = 2,

RoomID_cathedral_quire = 0,
RoomID_cathedral_organ_console = 1,
RoomID_garden_tree = 2,
RoomID_art_studio_front = 3,
RoomID_plaza_southeast = 4,
RoomID_cathedral_vestry = 5,
RoomID_thorn_lane_east = 6,
RoomID_plant_shop_front = 7,
RoomID_restaurant_front = 8,
RoomID_bar_cellar = 9,
RoomID_inn_room_3 = 10,
RoomID_crypt_room_1 = 11,
RoomID_cathedral_front = 12,
RoomID_bell_tower_programming_room = 13,
RoomID_garden_fountain = 14,
RoomID_concert_hall_front = 15,
RoomID_cathedral_apse = 16,
RoomID_bell_tower_storage_room = 17,
RoomID_cathedral_transept_left = 18,
RoomID_bakery_kitchen = 19,
RoomID_tailor_shop_front = 20,
RoomID_library_front = 21,
RoomID_inn_lobby = 22,
RoomID_inn_room_1 = 23,
RoomID_art_studio = 24,
RoomID_graveyard = 25,
RoomID_bakery_front = 26,
RoomID_bell_tower_lookout = 27,
RoomID_dark_alley = 28,
RoomID_plant_shop_greenhouse = 29,
RoomID_workshop = 30,
RoomID_bridge = 31,
RoomID_cathedral_maintenance_room = 32,
RoomID_plaza_northwest = 33,
RoomID_cathedral_nave = 34,
RoomID_bell_tower_playing_room = 35,
RoomID_thorn_lane_west = 36,
RoomID_shop_front = 37,
RoomID_bakery = 38,
RoomID_bench = 39,
RoomID_inn_front = 40,
RoomID_plant_shop = 41,
RoomID_bell_tower_belfrey = 42,
RoomID_inn_room_2 = 43,
RoomID_library = 44,
RoomID_garden_lawn = 45,
RoomID_shop = 46,
RoomID_bar = 47,
RoomID_bar_billiard_room = 48,
RoomID_tailor_shop = 49,
RoomID_plaza_southwest = 50,
RoomID_cathedral_transept_right = 51,
RoomID_bar_front = 52,
RoomID_inn_hallway = 53,
RoomID_workshop_front = 54,
RoomID_thorn_lane = 55,
RoomID_james_street = 56,
RoomID_TOTAL = 57,

ItemID_leather_sheet = 0,
ItemID_town_map = 1,
ItemID_carillon_page_2 = 2,
ItemID_ferns = 3,
ItemID_plaza_southwest_cathedral = 4,
ItemID_wheat_bread = 5,
ItemID_plaza_southeast_ground = 6,
ItemID_plant_pot = 7,
ItemID_scindapsus = 8,
ItemID_ghost_albert = 9,
ItemID_james_street_bushes = 10,
ItemID_organ_key = 11,
ItemID_calatheas = 12,
ItemID_muffins = 13,
ItemID_bell_tower_key = 14,
ItemID_plant_shop_front_vines = 15,
ItemID_plant_shop_front_doorknob = 16,
ItemID_carillon_pages_ghostly_congregation = 17,
ItemID_bell_tower_clavier = 18,
ItemID_green_plants = 19,
ItemID_workshop_front_doors = 20,
ItemID_workshop_front_building = 21,
ItemID_churros = 22,
ItemID_ritual_book = 23,
ItemID_carillon_page_3 = 24,
ItemID_inn_room_3_window = 25,
ItemID_cathedral_maintenance_room_organ_bellows = 26,
ItemID_garden_shovel = 27,
ItemID_organ_pipes = 28,
ItemID_ghost_orb = 29,
ItemID_apple_pie = 30,
ItemID_inn_lobby_cat = 31,
ItemID_philodendron_micans = 32,
ItemID_plaza_southeast_trees = 33,
ItemID_ritual_candles = 34,
ItemID_james_street_cathedral = 35,
ItemID_plaza_southwest_bell_tower = 36,
ItemID_workshop_front_tiles = 37,
ItemID_carillon_pages_bench_ghost = 38,
ItemID_carillon_page_1 = 39,
ItemID_carillon_page_4 = 40,
ItemID_plaza_southeast_cathedral = 41,
ItemID_carillon_pages_church_robes = 42,
ItemID_honeyed_almond_pastries = 43,
ItemID_umbrella = 44,
ItemID_bread_crumbs = 45,
ItemID_cathedral_organ_console_organ_console = 46,
ItemID_plant_shop_front_door = 47,
ItemID_croissants = 48,
ItemID_carillon_pages_singing_ghost = 49,
ItemID_inn_lobby_plant_pot = 50,
ItemID_cathedral_maintenance_room_organ_pipes = 51,
ItemID_garden_gloves = 52,
ItemID_carillon_pages_magic_staff = 53,
ItemID_carillon_page_5 = 54,
ItemID_ghost_coin = 55,
ItemID_workshop_front_workers = 56,
ItemID_james_street_bell_tower = 57,
ItemID_inn_room_1_window = 58,
ItemID_lantern = 59,
ItemID_TOTAL = 60,

AreaID_art_studio = 0,
AreaID_bakery = 1,
AreaID_bar = 2,
AreaID_bell_tower = 3,
AreaID_cathedral = 4,
AreaID_concert_hall = 5,
AreaID_dark_alley = 6,
AreaID_bench = 7,
AreaID_garden_lawn = 8,
AreaID_garden_tree = 9,
AreaID_garden_fountain = 10,
AreaID_graveyard = 11,
AreaID_inn = 12,
AreaID_plant_shop = 13,
AreaID_southeast_plaza = 14,
AreaID_southwest_plaza = 15,
AreaID_northwest_plaza = 16,
AreaID_restaurant = 17,
AreaID_shop = 18,
AreaID_thorn_lane = 19,
AreaID_east_thorn_lane = 20,
AreaID_west_thorn_lane = 21,
AreaID_tailor = 22,
AreaID_library = 23,
AreaID_TOTAL = 24,

};
global const char *SoundEffectNameTable[] = {
"sound_perform_ritual",
"sound_menu_move",
"sound_item_bought",
"sound_bell_tower_play",
"sound_item_dropped",
"sound_bellows_repaired",
"sound_test_music",
"sound_item_eaten",
"sound_move",
"sound_pipes_repaired",
"sound_open_door",
"sound_item_fed",
"sound_read",
"sound_open_map",
"sound_organ_play_broken",
"sound_setup_candles",
"sound_close_map",
"sound_organ_play_repaired",
"sound_pray",
"sound_item_taken",
};
global const char *FontNameTable[] = {
"font_fancy",
"font_basic",
"font_basic_bold",
"font_basic2",
"font_basic_lowercase",
};
global const char *VariableNameTable[] = {
"goto_specific",
"examine_invalid",
"locked",
"repair_cant",
"auto_unlock",
"setup_candles_carillon_pages",
"repair_not_broken",
"carillon_pages_bench_ghost_following",
"move_invalid_room",
"use_dont_know",
"move_invalid_all",
"setup_candles_cant",
"use_dont_have",
"carillon_pages_cathedral_singing",
"exit_where",
"perform_ritual_carillon_pages_inactive",
"undo_message",
"enter_where",
"redo_message",
"buy_callback_prompt",
"event_carillon_pages",
"ghost_enter",
"perform_ritual_carillon_pages_wrong_room",
"buy_callback_no",
"ghost_leave",
"theme",
"event_ghost_playing_organ",
"take_buy",
"feed_no_eater",
"take_buy_prompt",
"feed_no_food",
"perform_ritual_carillon_pages_no_book",
"buy_static",
"pray_response",
"start_room",
"buy_free",
"pray_carillon_pages_bench",
"buy_prompt",
"buy_too_poor",
"perform_ritual_carillon_pages_no_candles",
"invalid_command",
"pray_carillon_pages_cathedral",
"eat_cant",
"ambiguous_items",
"eat_invalid",
"room_too_small",
"examine_none",
"feed_carillon_pages_bench_ghost_pie",
"perform_ritual_carillon_pages_successful",
};
global const char *ThemeNameTable[] = {
"theme_default",
"theme_planty",
};
global const char *RoomNameTable[] = {
"cathedral_quire",
"cathedral_organ_console",
"garden_tree",
"art_studio_front",
"plaza_southeast",
"cathedral_vestry",
"thorn_lane_east",
"plant_shop_front",
"restaurant_front",
"bar_cellar",
"inn_room_3",
"crypt_room_1",
"cathedral_front",
"bell_tower_programming_room",
"garden_fountain",
"concert_hall_front",
"cathedral_apse",
"bell_tower_storage_room",
"cathedral_transept_left",
"bakery_kitchen",
"tailor_shop_front",
"library_front",
"inn_lobby",
"inn_room_1",
"art_studio",
"graveyard",
"bakery_front",
"bell_tower_lookout",
"dark_alley",
"plant_shop_greenhouse",
"workshop",
"bridge",
"cathedral_maintenance_room",
"plaza_northwest",
"cathedral_nave",
"bell_tower_playing_room",
"thorn_lane_west",
"shop_front",
"bakery",
"bench",
"inn_front",
"plant_shop",
"bell_tower_belfrey",
"inn_room_2",
"library",
"garden_lawn",
"shop",
"bar",
"bar_billiard_room",
"tailor_shop",
"plaza_southwest",
"cathedral_transept_right",
"bar_front",
"inn_hallway",
"workshop_front",
"thorn_lane",
"james_street",
};
global const char *ItemNameTable[] = {
"leather_sheet",
"town_map",
"carillon_page_2",
"ferns",
"plaza_southwest_cathedral",
"wheat_bread",
"plaza_southeast_ground",
"plant_pot",
"scindapsus",
"ghost_albert",
"james_street_bushes",
"organ_key",
"calatheas",
"muffins",
"bell_tower_key",
"plant_shop_front_vines",
"plant_shop_front_doorknob",
"carillon_pages_ghostly_congregation",
"bell_tower_clavier",
"green_plants",
"workshop_front_doors",
"workshop_front_building",
"churros",
"ritual_book",
"carillon_page_3",
"inn_room_3_window",
"cathedral_maintenance_room_organ_bellows",
"garden_shovel",
"organ_pipes",
"ghost_orb",
"apple_pie",
"inn_lobby_cat",
"philodendron_micans",
"plaza_southeast_trees",
"ritual_candles",
"james_street_cathedral",
"plaza_southwest_bell_tower",
"workshop_front_tiles",
"carillon_pages_bench_ghost",
"carillon_page_1",
"carillon_page_4",
"plaza_southeast_cathedral",
"carillon_pages_church_robes",
"honeyed_almond_pastries",
"umbrella",
"bread_crumbs",
"cathedral_organ_console_organ_console",
"plant_shop_front_door",
"croissants",
"carillon_pages_singing_ghost",
"inn_lobby_plant_pot",
"cathedral_maintenance_room_organ_pipes",
"garden_gloves",
"carillon_pages_magic_staff",
"carillon_page_5",
"ghost_coin",
"workshop_front_workers",
"james_street_bell_tower",
"inn_room_1_window",
"lantern",
};

#endif // GENERATED_ASSET_ID_H
